<?php



/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends Doctrine\ORM\EntityRepository
{

  function getMoyenne($id){

      $query_builder = $this->_em->createQueryBuilder();

      $query_builder->select('f')
      ->from('\Note', 'f')
      ->where('f.idSalarie = :id_salarie and f.points is not null')
      ->setParameter('id_salarie', $id);

      $query = $query_builder->getQuery();
      $notes = $query->getResult();

      $total = 0;
      $coefTotal = 0;

      foreach ( $notes as $note ) {

          $coefTotal += $note->getCoefficient();
          $points = $note->getPoints() / $note->getDenominateur() * 20 * $note->getCoefficient();
          $total +=$points;

      }

      $moyenne = $total / $coefTotal;

      return $moyenne;
  }
}
