<?php



/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends Doctrine\ORM\EntityRepository
{
  function getSallesByMatieres($id){

      $seances = $this->_em->getRepository('\Seance')->findBy(array('idMatiere' => $id));

      $salles = [];

      foreach( $seances as $seance ) {
          $sessions = $seance->getSessions();

          foreach($sessions as $session) {
              $reservations = $session->getReservations();
              foreach ( $reservations as $reservation ){
                  $salle = $reservation->getSalle()->getNom();
                  $salles[] = $salle;
              }

          }
      }

      return $salles;

  }
}
